### ISSUE TITLE
关于 cqps 和 go-cqhttp 的自启

### ISSUE THREAD

**Issue by Tsuk1ko** [Miuzarte/cq-picsearcher-bot-deployment#1]
go-cqhttp 其实也可以交给 pm2 去守护运行，例如在 go-cqhttp 目录内创建 `ecosystem.config.js`

```js
module.exports = {
  apps: [
    {
      name: 'go-cqhttp',
      script: './go-cqhttp',
      autorestart: true,
      max_restarts: 10,
      min_uptime: '10s',
      restart_delay: 5000,
      out_file: '/dev/null',
      error_file: '/dev/null',
    },
  ],
};
```

然后在 cqps 目录内执行

```bash
npx pm2 start /path/to/go-cqhttp/ecosystem.config.js
```

----------------------

https://pm2.io/docs/runtime/guide/startup-hook/

另外 pm2 本身就可以自启，在 cqps 目录内执行

```
npx pm2 save
npx pm2 startup
```

**Comment by Miuzarte** [comment]
> go-cqhttp 其实也可以交给 pm2 去守护运行，例如在 go-cqhttp 目录内创建 `ecosystem.config.js`
> 
> ```js
> module.exports = {
>   apps: [
>     {
>       name: 'go-cqhttp',
>       script: './go-cqhttp',
>       autorestart: true,
>       max_restarts: 10,
>       min_uptime: '10s',
>       restart_delay: 5000,
>       out_file: '/dev/null',
>       error_file: '/dev/null',
>     },
>   ],
> };
> ```

pm2守护运行的gocqhttp如何调出来看日志

**Comment by Tsuk1ko** [comment]
go-cqhttp 自带日志，在它自己的 logs 目录内，`tail -f` 一下就好了，所以我这里的配置文件没有让 pm2 记录它的日志

**Comment by Tsuk1ko** [comment]
如果正常记录日志的话，`npx pm2 logs <name>` 就可以查看日志

**Comment by Miuzarte** [comment]
> go-cqhttp 自带日志，在它自己的 logs 目录内，`tail -f` 一下就好了，所以我这里的配置文件没有让 pm2 记录它的日志

我个人还是喜欢像Windows一样留个窗口开关看东西方便，还是用screen吧，反正这程序也不需要保活

**Comment by Tsuk1ko** [comment]
我就是因为遇到过它崩溃过所以我自己才守护了，我原来也是 screen 的😂

虽然是小概率事件

**Comment by Miuzarte** [comment]
> 另外 pm2 本身就可以自启，在 cqps 目录内执行
> 
> ```
> npx pm2 save
> npx pm2 startup
> ```

```
# pm2 save
[PM2] Saving current process list...
[PM2] Successfully saved in /root/.pm2/dump.pm2
```
```
# pm2 startup
[PM2] Init System found: systemd
Platform systemd
Template
[Unit]
Description=PM2 process manager
Documentation=https://pm2.keymetrics.io/
After=network.target

[Service]
Type=forking
User=root
LimitNOFILE=infinity
LimitNPROC=infinity
LimitCORE=infinity
Environment=PATH=/usr/local/nginx/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
Environment=PM2_HOME=/root/.pm2
PIDFile=/root/.pm2/pm2.pid
Restart=on-failure

ExecStart=/usr/lib/node_modules/pm2/bin/pm2 resurrect
ExecReload=/usr/lib/node_modules/pm2/bin/pm2 reload all
ExecStop=/usr/lib/node_modules/pm2/bin/pm2 kill

[Install]
WantedBy=multi-user.target

Target path
/etc/systemd/system/pm2-root.service
Command list
[ 'systemctl enable pm2-root' ]
[PM2] Writing init configuration in /etc/systemd/system/pm2-root.service
[PM2] Making script booting at startup...
[PM2] [-] Executing: systemctl enable pm2-root...
[PM2] [v] Command successfully executed.
+---------------------------------------+
[PM2] Freeze a process list on reboot via:
$ pm2 save

[PM2] Remove init script via:
$ pm2 unstartup systemd

```
reboot之后pm2 list显示stop,机器人也没有回复已上线

**Comment by Tsuk1ko** [comment]
看样子需要全局安装 pm2，它创建的这个服务不会自动检测局部安装的……

```bash
yarn global add pm2
# 或
npm i pm2 -g
```

**Comment by Miuzarte** [comment]
> 看样子需要全局安装 pm2，它创建的这个服务不会自动检测局部安装的……
> 
> ```shell
> yarn global add pm2
> # 或
> npm i pm2 -g
> ```

之前已经是全局pm2了,刚刚试了下yarn的还是不行,这回reboot之后pm2 list是空的
~~我想摸了~~

**Comment by Tsuk1ko** [comment]
~那就摸了~
