### ISSUE TITLE
希望新增arm64架构的脚本

### ISSUE THREAD

**Issue by bearcloney** [Miuzarte/cq-picsearcher-bot-deployment#2]
大佬NB！！（破音）

**Comment by Miuzarte** [comment]
手机跑的Termux还是树莓派之类的跑的正常Linux发行版

前者可以pkg install nodejs(我试过能行)

后者我得周六去搞个arm的Ubuntu看看apt的nodejs能不能正常跑

**Comment by Miuzarte** [comment]
大概知道怎么通过二进制文件安装nodejs了,明天先摸出来丢手机上测试测试

**Comment by Miuzarte** [comment]
termux实测没救
![image](https://user-images.githubusercontent.com/66856838/120017134-13de0e80-c018-11eb-8b40-efbb56e8176b.png)

**Comment by Miuzarte** [comment]
proot了个Ubuntu也是没成功 不知道环境有啥问题,也不知道正经Ubuntu能不能用,我明天把脚本摸出来你自己试试口巴(
![image](https://user-images.githubusercontent.com/66856838/120022473-0710e900-c01f-11eb-8177-04a1d798e93e.png)

**Comment by Miuzarte** [comment]
release发了,去试试吧,good luck(

**Comment by bearcloney** [comment]
蟹蟹大佬，使用你的教程我已经基本成功了，我的设备是r2sopenwrt系统的，内置docker，在里面装了centos。也是到了安装nodejs就卡住，后来突发奇想Docker pull node:latest没想到成功了，go安在cent，pic按在nodejs，还在python里装了rss 
哈哈哈
